  
version: '3'

services:

  mysql-standalone:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=testroutes
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - 3306:3306
    volumes:
      - ./bd_spring_docker:/var/lib/mysql
    networks:
      - test-mysql
      
  route-service:
    image: demo-routes/routes_service
    networks:
      - test-mysql
    restart: on-failure
    depends_on:
      - mysql-standalone
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=mysql-standalone
      - DATABASE_USER=test
      - DATABASE_PASSWORD=test
      - DATABASE_NAME=testroutes
      - DATABASE_PORT=3306

  route-calculator:
    image: demo-routes/routes_calculator
    networks:
      - test-mysql
    restart: on-failure
    depends_on:
      - route-service
    ports:
      - 8081:8081
   
networks:
  test-mysql: 
