version: '3'
services:

  mysql-standalone:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=testroutes
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    ports:
      - 3306:3306
    volumes:
      - ./bd_spring_docker:/var/lib/mysql

  discovery-service:
    image: demo-routes/discovery-service
    ports:
      - 8761:8761

  routes-gateway:
    image: demo-routes/routes-gateway
    restart: on-failure
    depends_on:
      - discovery-service
    ports:
      - 8662:8662
    environment:
      - EUREKA_SERVER=http://discovery-service:8761/eureka

  routes-service:
    image: demo-routes/routes-service
    restart: on-failure
    depends_on:
      - mysql-standalone
      - routes-gateway
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=mysql-standalone
      - DATABASE_USER=test
      - DATABASE_PASSWORD=test
      - DATABASE_NAME=testroutes
      - DATABASE_PORT=3306
      - EUREKA_SERVER=http://discovery-service:8761/eureka

  routes-calculator:
    image: demo-routes/routes-calculator
    restart: on-failure
    depends_on:
      - routes-gateway
      - routes-service
    ports:
      - 8081:8081
    environment:
      - EUREKA_SERVER=http://discovery-service:8761/eureka
